# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49faa607138f416193b575b46082d9dbb8445a4a6bd5e8399d2445a732cbc959ad0d7a0b74e00b9d938ed8702e6b73b334e77e2d6e76a1e205b450d63fc2cc07

test:
  secret_key_base: 77002286ccbfa57dff8f84b1b1b0195284f8858ffaae844a3f5c97ae5df57d6e5d985cbe2a30b1d319d39cbb52ec165657fe4eb99a53ea2407211a331f76769f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
